// Generated by scripts/generate-plugins.mjs from plugins/specs/*.json - do not edit by hand.
import type { IDataObject } from 'n8n-workflow';

export interface PluginField {
	/** Node parameter name. */
	name: string;
	/** API query parameter it is sent as. */
	param: string;
	/** 0 means "no limit" in the node, so it is not sent. */
	skipZero?: boolean;
}

export interface OutputShape {
	/** Fields kept by Simplify; dot paths are flattened (`seller.username` -> `sellerUsername`), `path:name` renames. */
	simplified: string[];
	/** Always returned with Selected Fields when the item has them. */
	idFields?: string[];
}

export interface PluginOperation {
	endpoint: string;
	fixed: IDataObject;
	fields: PluginField[];
	/** Entries of the Options and Sort collections, by node parameter name. */
	collectionFields: Record<string, PluginField>;
	/** Response key (or dot path) holding the result list; without it the whole answer is one item. */
	listKey?: string;
	/** Several result lists, each entry tagged with its `type` (search results and ads). */
	listKeys?: { key: string; type: string }[];
	/** Response key (or dot path) holding the single record of a "get one" operation. */
	itemKey?: string;
	shape?: OutputShape;
}

export const PLUGIN_OPERATIONS: Record<string, PluginOperation> = {
	'airbnb:searchStays': {
		endpoint: '/travel/airbnb',
		fixed: {},
		fields: [
			{
				name: 'location',
				param: 'location',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			checkin: {
				name: 'checkin',
				param: 'checkin',
			},
			checkout: {
				name: 'checkout',
				param: 'checkout',
			},
			adults: {
				name: 'adults',
				param: 'adults',
			},
			room_type: {
				name: 'room_type',
				param: 'room_type',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'listings',
		shape: {
			simplified: [
				'id',
				'name',
				'roomType',
				'price',
				'priceLabel',
				'rating',
				'reviewCount',
				'badges',
				'url',
				'image',
			],
			idFields: ['id'],
		},
	},
	'airbnb:getListing': {
		endpoint: '/travel/airbnb-room',
		fixed: {},
		fields: [
			{
				name: 'room',
				param: 'room',
			},
		],
		collectionFields: {
			check_in: {
				name: 'check_in',
				param: 'check_in',
			},
			check_out: {
				name: 'check_out',
				param: 'check_out',
			},
			adults: {
				name: 'adults',
				param: 'adults',
			},
			children: {
				name: 'children',
				param: 'children',
			},
			infants: {
				name: 'infants',
				param: 'infants',
			},
			pets: {
				name: 'pets',
				param: 'pets',
			},
			currency: {
				name: 'currency',
				param: 'currency',
			},
			locale: {
				name: 'locale',
				param: 'locale',
			},
			include_reviews: {
				name: 'include_reviews',
				param: 'include_reviews',
			},
			max_reviews: {
				name: 'max_reviews',
				param: 'max_reviews',
			},
			reviews_sort: {
				name: 'reviews_sort',
				param: 'reviews_sort',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'id',
				'title',
				'url',
				'propertyType',
				'location.city',
				'rating.overall',
				'reviewsCount',
				'guests',
				'bedrooms',
				'price',
			],
			idFields: ['id'],
		},
	},
	'airbnb:getReviews': {
		endpoint: '/travel/airbnb-reviews',
		fixed: {},
		fields: [
			{
				name: 'room',
				param: 'room',
			},
			{
				name: 'max_reviews',
				param: 'max_reviews',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			since: {
				name: 'since',
				param: 'since',
			},
			locale: {
				name: 'locale',
				param: 'locale',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'reviews',
		shape: {
			simplified: [
				'id',
				'rating',
				'text',
				'translatedText',
				'language',
				'date',
				'stayDetail',
				'reviewer.name',
				'reviewer.location',
				'response',
			],
			idFields: ['id'],
		},
	},
	'alibaba:searchProducts': {
		endpoint: '/marketplace/alibaba-search',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			verified: {
				name: 'verified',
				param: 'verified',
			},
			verified_pro: {
				name: 'verified_pro',
				param: 'verified_pro',
			},
			trade_assurance: {
				name: 'trade_assurance',
				param: 'trade_assurance',
			},
			supplier_country: {
				name: 'supplier_country',
				param: 'supplier_country',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'productId',
				'title',
				'priceMin',
				'priceMax',
				'currency',
				'moq',
				'moqUnit',
				'supplier.name',
				'supplier.country',
				'url',
			],
			idFields: ['productId'],
		},
	},
	'alibaba:getProduct': {
		endpoint: '/marketplace/alibaba-product',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			product_id: {
				name: 'product_id',
				param: 'product_id',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'product',
		shape: {
			simplified: [
				'productId',
				'title',
				'priceMinUsd',
				'priceMaxUsd',
				'moq',
				'unit',
				'supplier.name',
				'supplier.country',
				'tradeAssurance',
				'url',
			],
			idFields: ['productId'],
		},
	},
	'aliExpress:searchProducts': {
		endpoint: '/goods/aliexpress-search',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'productId',
				'title',
				'price',
				'currency',
				'originalPrice',
				'rating',
				'orders',
				'url',
				'image',
			],
			idFields: ['productId'],
		},
	},
	'amazon:getProduct': {
		endpoint: '/marketplace/amazon-product',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			asin: {
				name: 'asin',
				param: 'asin',
			},
			marketplace: {
				name: 'marketplace',
				param: 'marketplace',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'asin',
				'title',
				'brand',
				'price',
				'currency',
				'inStock',
				'rating',
				'reviewCount',
				'url',
				'image',
			],
			idFields: ['asin'],
		},
	},
	'amazon:searchProducts': {
		endpoint: '/marketplace/amazon-search',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'marketplace',
				param: 'marketplace',
			},
			{
				name: 'page',
				param: 'page',
			},
		],
		collectionFields: {
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'asin',
				'title',
				'price',
				'currency',
				'listPrice',
				'rating',
				'reviewCount',
				'sponsored',
				'url',
				'image',
			],
			idFields: ['asin'],
		},
	},
	'amazon:getReviews': {
		endpoint: '/marketplace/amazon-reviews',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			asin: {
				name: 'asin',
				param: 'asin',
			},
			marketplace: {
				name: 'marketplace',
				param: 'marketplace',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'asin',
				'title',
				'rating',
				'reviewCount',
				'histogram',
				'customersSay.summary',
				'reviewsGated',
				'reviewsReturned',
				'reviews',
				'url',
			],
			idFields: ['asin'],
		},
	},
	'amazon:getBestSellers': {
		endpoint: '/marketplace/amazon-bestsellers',
		fixed: {},
		fields: [
			{
				name: 'category',
				param: 'category',
			},
			{
				name: 'marketplace',
				param: 'marketplace',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			list_type: {
				name: 'list_type',
				param: 'list_type',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'items',
		shape: {
			simplified: [
				'rank',
				'asin',
				'title',
				'price',
				'currency',
				'rating',
				'reviewsCount',
				'url',
				'image',
			],
			idFields: ['asin'],
		},
	},
	'appStore:getApp': {
		endpoint: '/apps/app-store',
		fixed: {
			mode: 'app',
		},
		fields: [
			{
				name: 'app_id',
				param: 'app_id',
			},
		],
		collectionFields: {
			country: {
				name: 'country',
				param: 'country',
			},
			lang: {
				name: 'lang',
				param: 'lang',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'app',
		shape: {
			simplified: [
				'appId',
				'title',
				'developer',
				'genre',
				'rating',
				'ratingsCount',
				'price',
				'version',
				'updated',
				'url',
			],
			idFields: ['appId'],
		},
	},
	'appStore:searchApps': {
		endpoint: '/apps/app-store',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			country: {
				name: 'country',
				param: 'country',
			},
			lang: {
				name: 'lang',
				param: 'lang',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'apps',
		shape: {
			simplified: [
				'appId',
				'title',
				'developer',
				'genre',
				'rating',
				'ratingsCount',
				'price',
				'version',
				'updated',
				'url',
			],
			idFields: ['appId'],
		},
	},
	'appStore:getReviews': {
		endpoint: '/apps/app-store',
		fixed: {
			mode: 'reviews',
		},
		fields: [
			{
				name: 'app_id',
				param: 'app_id',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			country: {
				name: 'country',
				param: 'country',
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'reviews',
	},
	'autoscout24:searchListings': {
		endpoint: '/vehicles/autoscout24',
		fixed: {},
		fields: [
			{
				name: 'make',
				param: 'make',
			},
			{
				name: 'model',
				param: 'model',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			fuel: {
				name: 'fuel',
				param: 'fuel',
			},
			transmission: {
				name: 'transmission',
				param: 'transmission',
			},
			price_from: {
				name: 'price_from',
				param: 'price_from',
				skipZero: true,
			},
			price_to: {
				name: 'price_to',
				param: 'price_to',
				skipZero: true,
			},
			year_from: {
				name: 'year_from',
				param: 'year_from',
				skipZero: true,
			},
			year_to: {
				name: 'year_to',
				param: 'year_to',
				skipZero: true,
			},
			mileage_to: {
				name: 'mileage_to',
				param: 'mileage_to',
				skipZero: true,
			},
			power_from: {
				name: 'power_from',
				param: 'power_from',
				skipZero: true,
			},
			power_to: {
				name: 'power_to',
				param: 'power_to',
				skipZero: true,
			},
			power_unit: {
				name: 'power_unit',
				param: 'power_unit',
			},
			country: {
				name: 'country',
				param: 'country',
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'listings',
		shape: {
			simplified: [
				'id',
				'make',
				'model',
				'title',
				'price.raw',
				'mileageKm',
				'firstRegistration',
				'fuel',
				'location.country',
				'url',
			],
			idFields: ['id'],
		},
	},
	'bestBuy:searchProducts': {
		endpoint: '/marketplace/bestbuy-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'sku',
				'title',
				'brand',
				'model',
				'price',
				'originalPrice',
				'rating',
				'reviewCount',
				'url',
				'image',
			],
			idFields: ['sku'],
		},
	},
	'bing:search': {
		endpoint: '/search/bing',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'pages_to_check',
				param: 'pages_to_check',
			},
		],
		collectionFields: {
			language: {
				name: 'language',
				param: 'language',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKeys: [
			{
				key: 'organic',
				type: 'organic',
			},
			{
				key: 'topAds',
				type: 'ad_top',
			},
			{
				key: 'bottomAds',
				type: 'ad_bottom',
			},
		],
	},
	'bing:searchImages': {
		endpoint: '/images/bing-search',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'pages',
				param: 'pages',
			},
		],
		collectionFields: {
			max_results: {
				name: 'max_results',
				param: 'max_results',
				skipZero: true,
			},
			language: {
				name: 'language',
				param: 'language',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'position',
				'title',
				'imageUrl',
				'sourcePageUrl',
				'sourceDomain',
				'sourceName',
				'width',
				'height',
				'thumbnailUrl',
				'bingImagesUrl',
			],
			idFields: ['imageUrl'],
		},
	},
	'booking:searchHotels': {
		endpoint: '/travel/booking',
		fixed: {},
		fields: [
			{
				name: 'location',
				param: 'location',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			checkin: {
				name: 'checkin',
				param: 'checkin',
			},
			checkout: {
				name: 'checkout',
				param: 'checkout',
			},
			adults: {
				name: 'adults',
				param: 'adults',
			},
			children: {
				name: 'children',
				param: 'children',
			},
			rooms: {
				name: 'rooms',
				param: 'rooms',
			},
			currency: {
				name: 'currency',
				param: 'currency',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'properties',
		shape: {
			simplified: [
				'id',
				'name',
				'price',
				'currency',
				'reviewScore',
				'reviewCount',
				'address',
				'city',
				'url',
				'image',
			],
			idFields: ['id'],
		},
	},
	'booking:getReviews': {
		endpoint: '/travel/booking-reviews',
		fixed: {},
		fields: [
			{
				name: 'hotel',
				param: 'hotel',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			languages: {
				name: 'languages',
				param: 'languages',
			},
			since: {
				name: 'since',
				param: 'since',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'reviews',
		shape: {
			simplified: [
				'id',
				'reviewDate',
				'rating',
				'title',
				'positiveText',
				'negativeText',
				'reviewer.name',
				'reviewer.country',
				'travelerType',
				'nights',
			],
			idFields: ['id'],
		},
	},
	'brave:search': {
		endpoint: '/search/brave',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'pages_to_check',
				param: 'pages_to_check',
			},
		],
		collectionFields: {
			language: {
				name: 'language',
				param: 'language',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKeys: [
			{
				key: 'organic',
				type: 'organic',
			},
			{
				key: 'topAds',
				type: 'ad_top',
			},
			{
				key: 'bottomAds',
				type: 'ad_bottom',
			},
		],
	},
	'capterra:getReviews': {
		endpoint: '/reviews/capterra',
		fixed: {
			mode: 'reviews',
		},
		fields: [
			{
				name: 'product',
				param: 'product',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'reviews',
		shape: {
			simplified: [
				'id',
				'title',
				'rating',
				'date',
				'pros',
				'cons',
				'comments',
				'reviewer.title',
				'reviewer.companySize',
				'url',
			],
			idFields: ['id'],
		},
	},
	'capterra:searchProducts': {
		endpoint: '/reviews/capterra',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'id',
				'name',
				'rating',
				'reviewCount',
				'description',
				'url',
				'reviewsUrl',
				'logo',
				'slug',
				'position',
			],
			idFields: ['id'],
		},
	},
	'craigslist:searchListings': {
		endpoint: '/marketplace/craigslist-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'site',
				param: 'site',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			category: {
				name: 'category',
				param: 'category',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'listings',
	},
	'duckduckgo:search': {
		endpoint: '/search/duckduckgo',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'pages_to_check',
				param: 'pages_to_check',
			},
		],
		collectionFields: {
			language: {
				name: 'language',
				param: 'language',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKeys: [
			{
				key: 'organic',
				type: 'organic',
			},
			{
				key: 'topAds',
				type: 'ad_top',
			},
			{
				key: 'bottomAds',
				type: 'ad_bottom',
			},
		],
	},
	'ebay:searchListings': {
		endpoint: '/marketplace/ebay-search',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'marketplace',
				param: 'marketplace',
			},
			{
				name: 'page',
				param: 'page',
			},
		],
		collectionFields: {
			page_size: {
				name: 'page_size',
				param: 'page_size',
			},
			condition: {
				name: 'condition',
				param: 'condition',
			},
			listing_type: {
				name: 'listing_type',
				param: 'listing_type',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			free_shipping: {
				name: 'free_shipping',
				param: 'free_shipping',
			},
			seller: {
				name: 'seller',
				param: 'seller',
			},
			category: {
				name: 'category',
				param: 'category',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'listingId',
				'title',
				'price',
				'currency',
				'shippingCost',
				'condition',
				'seller.username',
				'locationRaw',
				'url',
				'image',
			],
			idFields: ['listingId'],
		},
	},
	'etsy:searchListings': {
		endpoint: '/marketplace/etsy-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			include_sponsored: {
				name: 'include_sponsored',
				param: 'include_sponsored',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
	},
	'g2:searchProducts': {
		endpoint: '/reviews/g2',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'name',
				'slug',
				'vendor.name',
				'rating',
				'reviewCount',
				'description',
				'categories',
				'url',
				'image',
				'productId',
			],
			idFields: ['url'],
		},
	},
	'glassdoor:searchJobs': {
		endpoint: '/jobs/glassdoor',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			location: {
				name: 'location',
				param: 'location',
			},
			loc_id: {
				name: 'loc_id',
				param: 'loc_id',
				skipZero: true,
			},
			loc_type: {
				name: 'loc_type',
				param: 'loc_type',
			},
			radius: {
				name: 'radius',
				param: 'radius',
			},
			job_type: {
				name: 'job_type',
				param: 'job_type',
			},
			experience: {
				name: 'experience',
				param: 'experience',
			},
			from_age: {
				name: 'from_age',
				param: 'from_age',
			},
			min_salary: {
				name: 'min_salary',
				param: 'min_salary',
				skipZero: true,
			},
			remote: {
				name: 'remote',
				param: 'remote',
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'jobs',
		shape: {
			simplified: [
				'jobId',
				'title',
				'company',
				'location',
				'salary.min',
				'salary.max',
				'salary.currency',
				'salary.payPeriod',
				'ageInDays',
				'url',
			],
			idFields: ['jobId'],
		},
	},
	'glassdoor:getReviews': {
		endpoint: '/reviews/glassdoor',
		fixed: {},
		fields: [
			{
				name: 'company',
				param: 'company',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			rating: {
				name: 'rating',
				param: 'rating',
			},
			job_title: {
				name: 'job_title',
				param: 'job_title',
			},
			keyword: {
				name: 'keyword',
				param: 'keyword',
			},
			topic: {
				name: 'topic',
				param: 'topic',
			},
			employment_status: {
				name: 'employment_status',
				param: 'employment_status',
			},
			language: {
				name: 'language',
				param: 'language',
			},
			current_only: {
				name: 'current_only',
				param: 'current_only',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'reviews',
		shape: {
			simplified: [
				'id',
				'title',
				'rating',
				'pros',
				'cons',
				'jobTitle',
				'isCurrentEmployee',
				'location',
				'date',
				'url',
			],
			idFields: ['id'],
		},
	},
	'glassdoor:getSalaries': {
		endpoint: '/salaries/glassdoor',
		fixed: {},
		fields: [
			{
				name: 'company',
				param: 'company',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			job_title: {
				name: 'job_title',
				param: 'job_title',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'salaries',
	},
	'google:search': {
		endpoint: '/serpApi',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'pages_to_check',
				param: 'pages_to_check',
			},
		],
		collectionFields: {
			wait_after_load: {
				name: 'wait_after_load',
				param: 'wait_after_load',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKeys: [
			{
				key: 'organic',
				type: 'organic',
			},
			{
				key: 'topAds',
				type: 'ad_top',
			},
			{
				key: 'bottomAds',
				type: 'ad_bottom',
			},
			{
				key: 'aiOverview',
				type: 'ai_overview',
			},
		],
	},
	'google:searchImages': {
		endpoint: '/images/google-search',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'pages',
				param: 'pages',
			},
		],
		collectionFields: {
			max_results: {
				name: 'max_results',
				param: 'max_results',
				skipZero: true,
			},
			gl: {
				name: 'gl',
				param: 'gl',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
	},
	'google:searchJobs': {
		endpoint: '/jobs/google-jobs',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			location: {
				name: 'location',
				param: 'location',
			},
			hl: {
				name: 'hl',
				param: 'hl',
			},
			gl: {
				name: 'gl',
				param: 'gl',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'jobs',
		shape: {
			simplified: [
				'jobId',
				'title',
				'company',
				'location',
				'salary',
				'employmentType',
				'remote',
				'postedAge',
				'via',
				'shareUrl',
			],
			idFields: ['jobId'],
		},
	},
	'google:searchLocalBusinesses': {
		endpoint: '/maps/google-local',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
		],
		collectionFields: {
			hl: {
				name: 'hl',
				param: 'hl',
			},
			gl: {
				name: 'gl',
				param: 'gl',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'name',
				'rating',
				'reviews',
				'category',
				'address',
				'phone',
				'website',
				'hours',
				'price',
				'position',
			],
			idFields: ['name'],
		},
	},
	'google:getPlace': {
		endpoint: '/maps/place-details',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			place_id: {
				name: 'place_id',
				param: 'place_id',
			},
			feature_id: {
				name: 'feature_id',
				param: 'feature_id',
			},
			hl: {
				name: 'hl',
				param: 'hl',
			},
			gl: {
				name: 'gl',
				param: 'gl',
			},
			raw: {
				name: 'raw',
				param: 'raw',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'place',
		shape: {
			simplified: [
				'featureId',
				'name',
				'address',
				'phone',
				'website',
				'rating',
				'reviewCount',
				'categories',
				'hours',
				'googleMapsUrl',
			],
			idFields: ['featureId'],
		},
	},
	'google:searchShopping': {
		endpoint: '/goods/google-shopping',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			gl: {
				name: 'gl',
				param: 'gl',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'products',
	},
	'google:getTrends': {
		endpoint: '/trends/google-trends',
		fixed: {},
		fields: [
			{
				name: 'keywords',
				param: 'keywords',
			},
		],
		collectionFields: {
			geo: {
				name: 'geo',
				param: 'geo',
			},
			timeframe: {
				name: 'timeframe',
				param: 'timeframe',
			},
			property: {
				name: 'property',
				param: 'property',
			},
			category: {
				name: 'category',
				param: 'category',
			},
			sections: {
				name: 'sections',
				param: 'sections',
			},
			region_resolution: {
				name: 'region_resolution',
				param: 'region_resolution',
			},
			include_low_volume: {
				name: 'include_low_volume',
				param: 'include_low_volume',
			},
			hl: {
				name: 'hl',
				param: 'hl',
			},
			tz: {
				name: 'tz',
				param: 'tz',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'keywords',
				'timeframe',
				'geo',
				'interestOverTime',
				'averages',
				'interestByRegion',
				'relatedQueries',
				'relatedTopics',
				'exploreUrl',
				'errors',
			],
			idFields: ['keywords'],
		},
	},
	'googlePlay:getApp': {
		endpoint: '/apps/google-play',
		fixed: {
			mode: 'app',
		},
		fields: [
			{
				name: 'app_id',
				param: 'app_id',
			},
		],
		collectionFields: {
			hl: {
				name: 'hl',
				param: 'hl',
			},
			gl: {
				name: 'gl',
				param: 'gl',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'app',
		shape: {
			simplified: [
				'appId',
				'title',
				'developer',
				'genre',
				'score',
				'ratings',
				'installs',
				'price',
				'updatedISO',
				'url',
			],
			idFields: ['appId'],
		},
	},
	'googlePlay:searchApps': {
		endpoint: '/apps/google-play',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			hl: {
				name: 'hl',
				param: 'hl',
			},
			gl: {
				name: 'gl',
				param: 'gl',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'apps',
		shape: {
			simplified: [
				'appId',
				'title',
				'developer',
				'genre',
				'score',
				'installs',
				'summary',
				'inAppPurchases',
				'icon',
				'url',
			],
			idFields: ['appId'],
		},
	},
	'homeDepot:searchProducts': {
		endpoint: '/marketplace/homedepot-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'itemId',
				'title',
				'brand',
				'modelNumber',
				'price',
				'originalPrice',
				'rating',
				'reviewCount',
				'url',
				'image',
			],
			idFields: ['itemId'],
		},
	},
	'immobilienscout24:searchProperties': {
		endpoint: '/realestate/immobilienscout24',
		fixed: {},
		fields: [
			{
				name: 'location',
				param: 'location',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			channel: {
				name: 'channel',
				param: 'channel',
			},
			property_type: {
				name: 'property_type',
				param: 'property_type',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			min_rooms: {
				name: 'min_rooms',
				param: 'min_rooms',
				skipZero: true,
			},
			max_rooms: {
				name: 'max_rooms',
				param: 'max_rooms',
				skipZero: true,
			},
			min_area: {
				name: 'min_area',
				param: 'min_area',
				skipZero: true,
			},
			max_area: {
				name: 'max_area',
				param: 'max_area',
				skipZero: true,
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'listings',
		shape: {
			simplified: [
				'id',
				'title',
				'price',
				'priceType',
				'warmRent',
				'rooms',
				'livingArea',
				'address',
				'realtor',
				'url',
			],
			idFields: ['id'],
		},
	},
	'indeed:searchJobs': {
		endpoint: '/jobs/indeed',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'country',
				param: 'country',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			location: {
				name: 'location',
				param: 'location',
			},
			radius: {
				name: 'radius',
				param: 'radius',
			},
			job_type: {
				name: 'job_type',
				param: 'job_type',
			},
			days: {
				name: 'days',
				param: 'days',
			},
			remote: {
				name: 'remote',
				param: 'remote',
			},
			start: {
				name: 'start',
				param: 'start',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'jobs',
		shape: {
			simplified: [
				'jobkey',
				'title',
				'company',
				'location',
				'remote',
				'salary.text',
				'salary.min',
				'salary.max',
				'datePosted',
				'url',
			],
			idFields: ['jobkey'],
		},
	},
	'instagram:getProfile': {
		endpoint: '/social/instagram',
		fixed: {},
		fields: [
			{
				name: 'username',
				param: 'username',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'data',
		shape: {
			simplified: [
				'username',
				'full_name',
				'verified',
				'biography',
				'followers',
				'following',
				'posts_count',
				'external_urls',
				'url',
				'recent_posts',
			],
			idFields: ['username'],
		},
	},
	'instagram:getPost': {
		endpoint: '/social/instagram',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'data',
		shape: {
			simplified: [
				'shortcode',
				'caption',
				'likes',
				'comments',
				'posted_at',
				'media_type',
				'author.username',
				'thumbnail_url',
				'video_url',
				'url',
			],
			idFields: ['shortcode'],
		},
	},
	'leboncoin:searchListings': {
		endpoint: '/marketplace/leboncoin-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			category: {
				name: 'category',
				param: 'category',
			},
			location: {
				name: 'location',
				param: 'location',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			page: {
				name: 'page',
				param: 'page',
			},
			include_sponsored: {
				name: 'include_sponsored',
				param: 'include_sponsored',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'listings',
		shape: {
			simplified: [
				'id',
				'title',
				'price',
				'currency',
				'city',
				'zipcode',
				'category',
				'date',
				'sellerType',
				'url',
			],
			idFields: ['id'],
		},
	},
	'linkedin:getCompany': {
		endpoint: '/companies/linkedin',
		fixed: {},
		fields: [
			{
				name: 'company',
				param: 'company',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'company',
		shape: {
			simplified: [
				'name',
				'companyId',
				'tagline',
				'industry',
				'companySize',
				'employeeCount',
				'followers',
				'headquarters',
				'website',
				'url',
			],
			idFields: ['companyId'],
		},
	},
	'linkedin:searchJobs': {
		endpoint: '/jobs/linkedin',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			location: {
				name: 'location',
				param: 'location',
			},
			geo_id: {
				name: 'geo_id',
				param: 'geo_id',
			},
			distance: {
				name: 'distance',
				param: 'distance',
				skipZero: true,
			},
			time_posted: {
				name: 'time_posted',
				param: 'time_posted',
			},
			workplace: {
				name: 'workplace',
				param: 'workplace',
			},
			job_type: {
				name: 'job_type',
				param: 'job_type',
			},
			experience: {
				name: 'experience',
				param: 'experience',
			},
			salary: {
				name: 'salary',
				param: 'salary',
			},
			enrich: {
				name: 'enrich',
				param: 'enrich',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'jobs',
		shape: {
			simplified: [
				'jobId',
				'title',
				'company',
				'location',
				'postedDate',
				'salary',
				'employmentType',
				'seniorityLevel',
				'description',
				'jobUrl',
			],
			idFields: ['jobId'],
		},
	},
	'linkedin:getJob': {
		endpoint: '/jobs/linkedin',
		fixed: {
			mode: 'detail',
		},
		fields: [
			{
				name: 'job_id',
				param: 'job_id',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'job',
		shape: {
			simplified: [
				'jobId',
				'title',
				'company',
				'location',
				'salary',
				'employmentType',
				'seniorityLevel',
				'applicants',
				'description',
				'jobUrl',
			],
			idFields: ['jobId'],
		},
	},
	'metaAdLibrary:getAds': {
		endpoint: '/ads/meta-ad-library',
		fixed: {},
		fields: [
			{
				name: 'advertiser',
				param: 'advertiser',
			},
			{
				name: 'max_ads',
				param: 'max_ads',
			},
		],
		collectionFields: {
			country: {
				name: 'country',
				param: 'country',
			},
			active_status: {
				name: 'active_status',
				param: 'active_status',
			},
			media_type: {
				name: 'media_type',
				param: 'media_type',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'ad_archive_id',
				'page_name',
				'ad_text',
				'title',
				'cta_text',
				'link_url',
				'display_format',
				'creatives',
				'platforms',
				'started_running',
			],
			idFields: ['ad_archive_id'],
		},
	},
	'mobileDe:searchListings': {
		endpoint: '/vehicles/mobile-de',
		fixed: {},
		fields: [
			{
				name: 'mobileDeMake',
				param: 'make',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			make_id: {
				name: 'make_id',
				param: 'make_id',
				skipZero: true,
			},
			fuel: {
				name: 'fuel',
				param: 'fuel',
			},
			price_min: {
				name: 'price_min',
				param: 'price_min',
				skipZero: true,
			},
			price_max: {
				name: 'price_max',
				param: 'price_max',
				skipZero: true,
			},
			year_min: {
				name: 'year_min',
				param: 'year_min',
				skipZero: true,
			},
			mileage_max: {
				name: 'mileage_max',
				param: 'mileage_max',
				skipZero: true,
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'listings',
		shape: {
			simplified: [
				'id',
				'title',
				'makeModel',
				'price',
				'currency',
				'firstRegistration',
				'mileage',
				'power.kw',
				'fuel',
				'url',
			],
			idFields: ['id'],
		},
	},
	'naukri:searchJobs': {
		endpoint: '/jobs/naukri',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			location: {
				name: 'location',
				param: 'location',
			},
			experience: {
				name: 'experience',
				param: 'experience',
			},
			days: {
				name: 'days',
				param: 'days',
			},
			remote: {
				name: 'remote',
				param: 'remote',
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'jobs',
		shape: {
			simplified: [
				'jobId',
				'title',
				'company',
				'location',
				'workMode',
				'experience',
				'salary.text',
				'skills',
				'postedDate',
				'url',
			],
			idFields: ['jobId'],
		},
	},
	'oopbuy:searchProducts': {
		endpoint: '/goods/oopbuy-search',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'page',
				param: 'page',
			},
		],
		collectionFields: {
			page_size: {
				name: 'page_size',
				param: 'page_size',
			},
			channel: {
				name: 'channel',
				param: 'channel',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'results',
	},
	'productHunt:getLeaderboard': {
		endpoint: '/products/producthunt',
		fixed: {
			mode: 'leaderboard',
		},
		fields: [
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			date: {
				name: 'date',
				param: 'date',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'id',
				'name',
				'tagline',
				'dailyRank',
				'votesCount',
				'commentsCount',
				'topics',
				'url',
				'productSlug',
				'featuredAt',
			],
			idFields: ['id'],
		},
	},
	'productHunt:searchProducts': {
		endpoint: '/products/producthunt',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'id',
				'name',
				'tagline',
				'reviewsRating',
				'reviewsCount',
				'url',
				'slug',
				'thumbnail',
				'isNoLongerOnline',
			],
			idFields: ['id'],
		},
	},
	'productHunt:getTopicProducts': {
		endpoint: '/products/producthunt',
		fixed: {
			mode: 'topic',
		},
		fields: [
			{
				name: 'topic',
				param: 'topic',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'products',
	},
	'productHunt:getProduct': {
		endpoint: '/products/producthunt',
		fixed: {
			mode: 'detail',
		},
		fields: [
			{
				name: 'slug',
				param: 'slug',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'product',
		shape: {
			simplified: [
				'name',
				'tagline',
				'description',
				'websiteUrl',
				'url',
				'reviewsRating',
				'reviewsCount',
				'followersCount',
				'categories',
				'isNoLongerOnline',
			],
			idFields: ['id'],
		},
	},
	'redfin:searchProperties': {
		endpoint: '/realestate/redfin',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'location',
				param: 'location',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			url: {
				name: 'url',
				param: 'url',
			},
			status: {
				name: 'status',
				param: 'status',
			},
			sold_within_days: {
				name: 'sold_within_days',
				param: 'sold_within_days',
			},
			property_type: {
				name: 'property_type',
				param: 'property_type',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			beds: {
				name: 'beds',
				param: 'beds',
				skipZero: true,
			},
			baths: {
				name: 'baths',
				param: 'baths',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'homes',
		shape: {
			simplified: [
				'propertyId',
				'streetLine',
				'city',
				'zip',
				'price',
				'beds',
				'baths',
				'sqFt',
				'propertyType',
				'url',
			],
			idFields: ['propertyId'],
		},
	},
	'rightmove:searchProperties': {
		endpoint: '/realestate/rightmove',
		fixed: {},
		fields: [
			{
				name: 'location',
				param: 'location',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			channel: {
				name: 'channel',
				param: 'channel',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			min_bedrooms: {
				name: 'min_bedrooms',
				param: 'min_bedrooms',
				skipZero: true,
			},
			max_bedrooms: {
				name: 'max_bedrooms',
				param: 'max_bedrooms',
				skipZero: true,
			},
			property_type: {
				name: 'property_type',
				param: 'property_type',
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'properties',
		shape: {
			simplified: [
				'id',
				'address',
				'price.amount',
				'price.display',
				'bedrooms',
				'bathrooms',
				'propertyType',
				'agent.name',
				'addedOrReduced',
				'url',
			],
			idFields: ['id'],
		},
	},
	'shein:searchProducts': {
		endpoint: '/marketplace/shein-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'id',
				'title',
				'price',
				'originalPrice',
				'currency',
				'discountPercent',
				'rating',
				'reviewCount',
				'url',
				'image',
			],
			idFields: ['id'],
		},
	},
	'similarweb:getTrafficOverview': {
		endpoint: '/seo/similarweb',
		fixed: {},
		fields: [
			{
				name: 'domain',
				param: 'domain',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'domain',
				'snapshotDate',
				'totalVisits',
				'visitsChangePercent',
				'globalRank',
				'countryRank',
				'country',
				'category',
				'bounceRate',
				'avgVisitDuration',
			],
			idFields: ['domain'],
		},
	},
	'skyscanner:searchFlights': {
		endpoint: '/flights/skyscanner-quotes',
		fixed: {},
		fields: [
			{
				name: 'origin',
				param: 'origin',
			},
			{
				name: 'dest',
				param: 'dest',
			},
			{
				name: 'depart_date',
				param: 'depart_date',
			},
		],
		collectionFields: {
			return_date: {
				name: 'return_date',
				param: 'return_date',
			},
			adults: {
				name: 'adults',
				param: 'adults',
			},
			cabin: {
				name: 'cabin',
				param: 'cabin',
			},
			currency: {
				name: 'currency',
				param: 'currency',
			},
			market: {
				name: 'market',
				param: 'market',
			},
			locale: {
				name: 'locale',
				param: 'locale',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'itineraries.results',
		shape: {
			simplified: [
				'id',
				'price.raw',
				'price.formatted',
				'legs',
				'farePolicy',
				'isSelfTransfer',
				'score',
				'tags',
			],
			idFields: ['id'],
		},
	},
	'skyscanner:searchHotels': {
		endpoint: '/hotels/skyscanner-quotes',
		fixed: {},
		fields: [
			{
				name: 'destination',
				param: 'destination',
			},
			{
				name: 'checkin',
				param: 'checkin',
			},
			{
				name: 'checkout',
				param: 'checkout',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			adults: {
				name: 'adults',
				param: 'adults',
			},
			rooms: {
				name: 'rooms',
				param: 'rooms',
			},
			currency: {
				name: 'currency',
				param: 'currency',
			},
			market: {
				name: 'market',
				param: 'market',
			},
			locale: {
				name: 'locale',
				param: 'locale',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'hotels',
		shape: {
			simplified: [
				'id',
				'name',
				'stars.level',
				'cheapestPrice.pricePerNight.displayPrice',
				'cheapestPrice.priceTotal.displayPrice',
				'reviewSummary.score',
				'reviewSummary.reviewCount',
				'location.address',
				'distance.distanceDescription',
				'detailsPageUrl',
			],
			idFields: ['id'],
		},
	},
	'skyscanner:searchCarHire': {
		endpoint: '/carhire/skyscanner-quotes',
		fixed: {},
		fields: [
			{
				name: 'pickup',
				param: 'pickup',
			},
			{
				name: 'pickup_datetime',
				param: 'pickup_datetime',
			},
			{
				name: 'dropoff_datetime',
				param: 'dropoff_datetime',
			},
			{
				name: 'driver_age',
				param: 'driver_age',
			},
			{
				name: 'currency',
				param: 'currency',
			},
			{
				name: 'market',
				param: 'market',
			},
			{
				name: 'locale',
				param: 'locale',
			},
		],
		collectionFields: {
			dropoff: {
				name: 'dropoff',
				param: 'dropoff',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'quotes',
		shape: {
			simplified: [
				'guid',
				'car_name',
				'price',
				'vndr',
				'new_score',
				'seat',
				'bags',
				'fuel_pol',
				'pickup_type',
				'dplnk',
			],
			idFields: ['guid'],
		},
	},
	'southwest:searchFlights': {
		endpoint: '/flights/southwest-quotes',
		fixed: {},
		fields: [
			{
				name: 'origin',
				param: 'origin',
			},
			{
				name: 'dest',
				param: 'dest',
			},
			{
				name: 'depart_date',
				param: 'depart_date',
			},
		],
		collectionFields: {
			return_date: {
				name: 'return_date',
				param: 'return_date',
			},
			adults: {
				name: 'adults',
				param: 'adults',
			},
			fare_type: {
				name: 'fare_type',
				param: 'fare_type',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'data.searchResults.airProducts.details',
		shape: {
			simplified: [
				'flightNumbers',
				'originationAirportCode:origin',
				'destinationAirportCode:destination',
				'departureDateTime',
				'arrivalDateTime',
				'totalDuration:durationMinutes',
				'fareProducts.ADULT.WGA.fare.totalFare.value:wannaGetAwayPrice',
				'fareProducts.ADULT.PLU.fare.totalFare.value:wannaGetAwayPlusPrice',
				'fareProducts.ADULT.ANY.fare.totalFare.value:anytimePrice',
				'fareProducts.ADULT.BUS.fare.totalFare.value:businessSelectPrice',
			],
			idFields: ['flightNumbers'],
		},
	},
	'target:searchProducts': {
		endpoint: '/marketplace/target-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'products',
	},
	'telegram:getChannelPosts': {
		endpoint: '/social/telegram-channel',
		fixed: {},
		fields: [
			{
				name: 'channel',
				param: 'channel',
			},
			{
				name: 'max_posts',
				param: 'max_posts',
				skipZero: true,
			},
		],
		collectionFields: {
			q: {
				name: 'q',
				param: 'q',
			},
			since: {
				name: 'since',
				param: 'since',
			},
			before: {
				name: 'before',
				param: 'before',
				skipZero: true,
			},
			after: {
				name: 'after',
				param: 'after',
				skipZero: true,
			},
			post_id: {
				name: 'post_id',
				param: 'post_id',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'posts',
		shape: {
			simplified: [
				'id',
				'date',
				'text',
				'views',
				'media',
				'reactions',
				'forwardedFrom',
				'hashtags',
				'links',
				'url',
			],
			idFields: ['id'],
		},
	},
	'temu:searchProducts': {
		endpoint: '/goods/temu-search',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'max_results',
				param: 'limit',
			},
		],
		collectionFields: {
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'urls',
	},
	'temu:getProduct': {
		endpoint: '/goods/temu-product',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {},
		shape: {
			simplified: [
				'name',
				'price',
				'priceCurrency',
				'rating',
				'reviewCount',
				'availability',
				'variantGroupId',
				'images',
				'url',
			],
			idFields: ['url'],
		},
	},
	'threads:getProfile': {
		endpoint: '/social/threads-profile',
		fixed: {},
		fields: [
			{
				name: 'username',
				param: 'username',
			},
			{
				name: 'max_posts',
				param: 'max_posts',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
	},
	'tiktok:getProfile': {
		endpoint: '/social/tiktok-profile',
		fixed: {},
		fields: [
			{
				name: 'username',
				param: 'username',
			},
			{
				name: 'max_videos',
				param: 'max_videos',
			},
		],
		collectionFields: {
			video_details: {
				name: 'video_details',
				param: 'video_details',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'username',
				'nickname',
				'verified',
				'bio',
				'stats.followers',
				'stats.following',
				'stats.likes',
				'stats.videos',
				'profileUrl',
				'videos',
			],
			idFields: ['username'],
		},
	},
	'tiktok:getVideo': {
		endpoint: '/social/tiktok-video',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			include_transcript: {
				name: 'include_transcript',
				param: 'include_transcript',
			},
			transcript_language: {
				name: 'transcript_language',
				param: 'transcript_language',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		shape: {
			simplified: [
				'id',
				'description',
				'author.username',
				'createdAt',
				'stats.plays',
				'stats.likes',
				'stats.comments',
				'stats.shares',
				'url',
				'transcript',
			],
			idFields: ['id'],
		},
	},
	'tiktok:searchVideos': {
		endpoint: '/social/tiktok-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'id',
				'description',
				'author.username',
				'createdAt',
				'stats.plays',
				'stats.likes',
				'stats.comments',
				'stats.shares',
				'hashtags',
				'url',
			],
			idFields: ['id'],
		},
	},
	'tiktok:getHashtag': {
		endpoint: '/social/tiktok-hashtag',
		fixed: {},
		fields: [
			{
				name: 'hashtag',
				param: 'hashtag',
			},
			{
				name: 'max_videos',
				param: 'max_videos',
			},
		],
		collectionFields: {
			video_details: {
				name: 'video_details',
				param: 'video_details',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
	},
	'tiktok:getComments': {
		endpoint: '/social/tiktok-comments',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
			{
				name: 'max_comments',
				param: 'max_comments',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'comments',
		shape: {
			simplified: [
				'id',
				'text',
				'author.username',
				'author.nickname',
				'likes',
				'replyCount',
				'createdAt',
				'isCreator',
				'likedByCreator',
				'videoId',
			],
			idFields: ['id'],
		},
	},
	'tiktokShop:getProduct': {
		endpoint: '/social/tiktok-shop-product',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			product_id: {
				name: 'product_id',
				param: 'product_id',
			},
		},
		shape: {
			simplified: [
				'productId',
				'title',
				'price.current',
				'price.currency',
				'available',
				'rating',
				'reviewCount',
				'soldCount',
				'seller.name',
				'url',
			],
			idFields: ['productId'],
		},
	},
	'tiktokShop:searchProducts': {
		endpoint: '/social/tiktok-shop-search',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			category: {
				name: 'category',
				param: 'category',
			},
		},
		listKey: 'products',
		shape: {
			simplified: [
				'productId',
				'title',
				'price.current',
				'price.currency',
				'rating',
				'reviewCount',
				'soldCount',
				'brand',
				'seller.name',
				'url',
			],
			idFields: ['productId'],
		},
	},
	'tiktokShop:getStore': {
		endpoint: '/social/tiktok-shop-store',
		fixed: {},
		fields: [
			{
				name: 'store',
				param: 'store',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {},
	},
	'tripadvisor:getList': {
		endpoint: '/travel/tripadvisor',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'places',
		shape: {
			simplified: [
				'name',
				'type',
				'rating',
				'reviewCount',
				'priceRange',
				'cuisine',
				'address',
				'phone',
				'url',
				'image',
			],
			idFields: ['url'],
		},
	},
	'trustpilot:getReviews': {
		endpoint: '/reviews/trustpilot',
		fixed: {},
		fields: [
			{
				name: 'company',
				param: 'company',
			},
			{
				name: 'pages',
				param: 'pages',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			stars: {
				name: 'stars',
				param: 'stars',
			},
			date: {
				name: 'date',
				param: 'date',
			},
			language: {
				name: 'language',
				param: 'language',
			},
			search: {
				name: 'search',
				param: 'search',
			},
			verified: {
				name: 'verified',
				param: 'verified',
			},
			replies: {
				name: 'replies',
				param: 'replies',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'reviews',
		shape: {
			simplified: [
				'id',
				'rating',
				'title',
				'text',
				'author.name',
				'author.country',
				'date',
				'verified',
				'language',
				'reply.text',
			],
			idFields: ['id'],
		},
	},
	'vinted:searchListings': {
		endpoint: '/marketplace/vinted-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'marketplace',
				param: 'domain',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			price_from: {
				name: 'price_from',
				param: 'price_from',
				skipZero: true,
			},
			price_to: {
				name: 'price_to',
				param: 'price_to',
				skipZero: true,
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			order: {
				name: 'order',
				param: 'order',
			},
		},
		listKey: 'items',
	},
	'yahoo:search': {
		endpoint: '/search/yahoo',
		fixed: {},
		fields: [
			{
				name: 'keyword',
				param: 'keyword',
			},
			{
				name: 'pages_to_check',
				param: 'pages_to_check',
			},
		],
		collectionFields: {
			language: {
				name: 'language',
				param: 'language',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKeys: [
			{
				key: 'organic',
				type: 'organic',
			},
			{
				key: 'topAds',
				type: 'ad_top',
			},
			{
				key: 'bottomAds',
				type: 'ad_bottom',
			},
		],
	},
	'yahoo:searchImages': {
		endpoint: '/images/yahoo-search',
		fixed: {},
		fields: [
			{
				name: 'q',
				param: 'q',
			},
			{
				name: 'pages',
				param: 'pages',
			},
		],
		collectionFields: {
			max_results: {
				name: 'max_results',
				param: 'max_results',
				skipZero: true,
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'position',
				'title',
				'imageUrl',
				'sourcePageUrl',
				'sourceDomain',
				'sourceName',
				'width',
				'height',
				'thumbnailUrl',
				'yahooImagesUrl',
			],
			idFields: ['imageUrl'],
		},
	},
	'yelp:searchBusinesses': {
		endpoint: '/local/yelp',
		fixed: {
			mode: 'search',
		},
		fields: [
			{
				name: 'find_desc',
				param: 'find_desc',
			},
			{
				name: 'find_loc',
				param: 'find_loc',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			price: {
				name: 'price',
				param: 'price',
			},
			open_now: {
				name: 'open_now',
				param: 'open_now',
			},
			start: {
				name: 'start',
				param: 'start',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'businesses',
		shape: {
			simplified: [
				'businessId',
				'name',
				'rating',
				'reviewCount',
				'priceRange',
				'categories',
				'address',
				'city',
				'isAd',
				'url',
			],
			idFields: ['businessId'],
		},
	},
	'yelp:getBusiness': {
		endpoint: '/local/yelp',
		fixed: {
			mode: 'detail',
		},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'business',
		shape: {
			simplified: [
				'businessId',
				'name',
				'rating',
				'reviewCount',
				'priceRange',
				'categories',
				'phone',
				'address',
				'website',
				'hours',
			],
			idFields: ['businessId'],
		},
	},
	'yelp:getReviews': {
		endpoint: '/local/yelp-reviews',
		fixed: {},
		fields: [
			{
				name: 'business',
				param: 'business',
			},
			{
				name: 'max_reviews',
				param: 'max_reviews',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			language: {
				name: 'language',
				param: 'language',
			},
			rating: {
				name: 'rating',
				param: 'rating',
			},
			query: {
				name: 'query',
				param: 'query',
			},
			since: {
				name: 'since',
				param: 'since',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'reviews',
		shape: {
			simplified: [
				'id',
				'rating',
				'text',
				'date',
				'language',
				'user.name',
				'user.location',
				'ownerResponse',
				'helpfulVotes',
				'url',
			],
			idFields: ['id'],
		},
	},
	'youtube:getChannelVideos': {
		endpoint: '/content/youtube-channel',
		fixed: {},
		fields: [
			{
				name: 'channel',
				param: 'channel',
			},
			{
				name: 'max_videos',
				param: 'limit',
			},
		],
		collectionFields: {
			tab: {
				name: 'tab',
				param: 'tab',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'videos',
		shape: {
			simplified: [
				'videoId',
				'title',
				'viewCount',
				'views',
				'likeCount',
				'publishedAt',
				'durationSeconds',
				'description',
				'url',
				'thumbnail',
			],
			idFields: ['videoId'],
		},
	},
	'youtube:getComments': {
		endpoint: '/content/youtube-comments',
		fixed: {},
		fields: [
			{
				name: 'video',
				param: 'video',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'comments',
		shape: {
			simplified: [
				'commentId',
				'author',
				'text',
				'likeCount',
				'replyCount',
				'publishedTimeText',
				'isPinned',
				'isHearted',
				'isUploader',
				'authorChannelId',
			],
			idFields: ['commentId'],
		},
	},
	'youtube:search': {
		endpoint: '/content/youtube-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			type: {
				name: 'type',
				param: 'type',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'results',
		shape: {
			simplified: [
				'type',
				'videoId',
				'title',
				'channel.name',
				'viewCount',
				'publishedText',
				'lengthSeconds',
				'descriptionSnippet',
				'isLive',
				'url',
			],
			idFields: ['videoId'],
		},
	},
	'zalando:searchProducts': {
		endpoint: '/marketplace/zalando-search',
		fixed: {},
		fields: [
			{
				name: 'query',
				param: 'query',
			},
			{
				name: 'marketplace',
				param: 'domain',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		listKey: 'products',
	},
	'zillow:searchProperties': {
		endpoint: '/realestate/zillow',
		fixed: {},
		fields: [
			{
				name: 'location',
				param: 'location',
			},
			{
				name: 'max_results',
				param: 'max_results',
			},
		],
		collectionFields: {
			status: {
				name: 'status',
				param: 'status',
			},
			home_type: {
				name: 'home_type',
				param: 'home_type',
			},
			min_price: {
				name: 'min_price',
				param: 'min_price',
				skipZero: true,
			},
			max_price: {
				name: 'max_price',
				param: 'max_price',
				skipZero: true,
			},
			beds: {
				name: 'beds',
				param: 'beds',
				skipZero: true,
			},
			baths: {
				name: 'baths',
				param: 'baths',
				skipZero: true,
			},
			page: {
				name: 'page',
				param: 'page',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
			sort: {
				name: 'sort',
				param: 'sort',
			},
		},
		listKey: 'homes',
		shape: {
			simplified: [
				'zpid',
				'address',
				'price',
				'beds',
				'baths',
				'area',
				'homeType',
				'zestimate',
				'daysOnZillow',
				'url',
			],
			idFields: ['zpid'],
		},
	},
	'zillow:getProperty': {
		endpoint: '/realestate/zillow-detail',
		fixed: {},
		fields: [
			{
				name: 'url',
				param: 'url',
			},
		],
		collectionFields: {
			zpid: {
				name: 'zpid',
				param: 'zpid',
			},
			proxy_country: {
				name: 'proxy_country',
				param: 'proxy_country',
			},
		},
		itemKey: 'property',
		shape: {
			simplified: [
				'zpid',
				'address',
				'price',
				'statusText',
				'beds',
				'baths',
				'area',
				'yearBuilt',
				'zestimate',
				'url',
			],
			idFields: ['zpid'],
		},
	},
};
